name: CapitolTrades Daily Update

on:
  schedule:
    - cron: '0 8 * * *'  # Dagelijks om 08:00 UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data update script
      env:
        APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
      run: python update_capitol_data.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add sample_data.csv UPDATE_LOG.md
        git commit -m "Automatisch bijgewerkt via CapitolTrades API"
        git push
